---

- name: Install load balancer packages
  ansible.builtin.package:
    name: "{{ load_balancer_packages }}"
    state: present

- name: Configure haproxy load balancing
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

- name: Enable Haproxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

...    