---

networks:
  default:
      name: example.com

services:

  control:
    image: quay.io/tonykay/vmlet-rhel-8-ansible-control
    container_name: control
    hostname: control
    ports:
      - "2222:22"
    privileged: true
      #volumes:
      # - "../bind_mounts/ssh:/opt/app-root/src/.ssh:z,ro"
    
  frontend:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: frontend
    hostname: frontend
    ports:
      - "8080:80"
    privileged: true

  app-01:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: app-01
    hostname: app-01
    privileged: true

  app-02:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: app-02
    hostname: app-02
    privileged: true

  database-01:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: database-01
    hostname: database-01
    privileged: true

...
