---

- name: Disable any postgres module repos
  command: dnf -qy module disable postgresql

- name: Install Postgres packages
  ansible.builtin.dnf:
    name: "{{ __package }}"
    state: present
    enablerepo:
      - pgdg12
    disable_gpg_check: true
  loop: 
    - "{{ postgres_rhel8_repo }}"        
    - "{{ postgres_packages }}"
  loop_control:
    loop_var: __package

- name: Check if Postgres initialized
  ansible.builtin.stat:
    path: "{{ postgres_12_data_dir }}/PG_VERSION"
  register: r_postgres_init_dir_state

- when: not r_postgres_init_dir_state.stat.exists
  name: Run Postgres initdb to initialize if postgres not initialized
  ansible.builtin.command: "{{ postgres_12_bin_path }}/postgresql-12-setup initdb"
  notify: restart_postgres

- name: Setup Postgres for remote password auth
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_12_data_dir }}/pg_hba.conf"
  notify: restart_postgres

- name: Setup Postgres to listen on network interfaces
  ansible.builtin.lineinfile:
    dest: "{{ postgres_12_data_dir }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertafter: "#listen_addresses"
  notify: restart_postgres

- name: Setup Postgres as started and enabled on boot.
  ansible.builtin.service:
    name: "{{ postgres_service }}"
    state: "{{ postgres_service_state | default('started') }}"
    enabled: "{{ postgres_service_enabled | default(true) }}"

- name: Configure Postgres resources, user, database etc 
  block:

    - name: Setup Postgres database(s) 
      community.postgresql.postgresql_db:
        name: "{{ __database.name }}"
        state: "{{ __database.state | default('present') }}"
      loop: "{{ postgres_databases }}"
      loop_control:
        loop_var: __database

    - name: Create Postgres user#(s) 
      community.postgresql.postgresql_user:
        name: "{{ __user.name }}"
        password: "{{ __user.password | default(omit) }}"
        encrypted: true # "{{ __user.encrypted | default(omit) }}"
        priv: "{{ __user.priv | default(omit) }}"
        db: "{{ __user.database | default(omit) }}"
        # role_attr_flags: "{{ __user.role_attr_flags | default(omit) }}"
        state: "{{ __user.state | default('present') }}"
      loop: "{{ postgres_users }}"
      loop_control:
        loop_var: __user
      no_log: "{{ postgres_user_no_log_state | default(false) }}" 

  become_user: "{{ postgres_user }}"

